/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AssetRetentionHolds {
  asset_id: number;
  created_at: Generated<Date>;
  created_by: number;
  expires_at: Date | null;
  hold_id: string;
  hold_type: string;
  incident_id: string | null;
  reason: string;
  released_at: Date | null;
  starts_at: Date;
}

export interface AutomationRunEvents {
  details_json: Json | null;
  event_id: string;
  event_type: string;
  from_state: string | null;
  occurred_at: Date;
  run_id: string;
  run_item_id: string | null;
  to_state: string | null;
}

export interface AutomationRunItems {
  capture_id: string;
  category: string;
  created_at: Generated<Date>;
  current_attempt_id: string | null;
  error_code: string | null;
  error_detail: string | null;
  finished_at: Date | null;
  ordinal: number;
  outcome: string | null;
  reservation_id: string | null;
  row_version: Generated<number>;
  run_id: string;
  run_item_id: string;
  started_at: Date | null;
  state: string;
}

export interface AutomationRuns {
  accepted: Generated<number>;
  active_target_guild_id: number | null;
  awaiting_hero: Generated<number>;
  blob_eligible: Generated<number>;
  blob_purged: Generated<number>;
  consumed: Generated<number>;
  created_at: Generated<Date>;
  decision_id: string | null;
  discord_sent: Generated<number>;
  duplicate: Generated<number>;
  finished_at: Date | null;
  guild_configuration_version_id: number | null;
  hero_error: Generated<number>;
  late_result_count: Generated<number>;
  no_usable_response: Generated<number>;
  not_validating: Generated<number>;
  operational_finished_at: Date | null;
  origin_guild_id: number;
  platform_configuration_version_id: number | null;
  priority: number;
  quota_after: number | null;
  quota_before: number | null;
  reporting_cutoff_at: Date | null;
  reserved: Generated<number>;
  row_version: Generated<number>;
  run_id: string;
  season_id: string;
  selected: Generated<number>;
  send_failed: Generated<number>;
  started_at: Date;
  state: string;
  stop_reason: string | null;
  stop_requested_at: Date | null;
  target_guild_id: number;
  technical_quarantine: Generated<number>;
  terminal_reason: string | null;
  throughput_per_hour: Decimal | null;
  trigger_type: string;
  triggered_by_actor_id: number | null;
  triggered_by_actor_type: string;
  unknown_correlated: Generated<number>;
  validations_gained: Generated<number>;
  yield_rate: Decimal | null;
}

export interface BlobPurgeEvents {
  asset_id: number;
  bytes: number | null;
  details_json: Json | null;
  event_id: string;
  event_type: string;
  occurred_at: Date;
  purge_job_id: string;
  reason: string | null;
}

export interface BlobPurgeJobs {
  active_asset_id: number | null;
  asset_id: number;
  attempt_count: Generated<number>;
  bytes_deleted: number | null;
  bytes_expected: number | null;
  completed_at: Date | null;
  created_at: Generated<Date>;
  eligibility_reason: string;
  eligible_at: Date;
  last_error: string | null;
  lease_expires_at: Date | null;
  lease_fencing_token: number | null;
  lease_owner_instance_id: string | null;
  purge_job_id: string;
  row_version: Generated<number>;
  started_at: Date | null;
  state: string;
}

export interface CaptureAssetBlobs {
  asset_id: number;
  created_at: Generated<Date>;
  encoding: Generated<string>;
  image_data: Buffer;
  stored_sha256: Buffer;
  stored_size_bytes: number;
}

export interface CaptureAssets {
  asset_id: Generated<number>;
  blob_eligible_at: Date | null;
  blob_purge_reason: string | null;
  blob_purged_at: Date | null;
  blob_state: string;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  height_px: number | null;
  last_referenced_at: Date;
  mime_type: string;
  original_size_bytes: number;
  sha256: Buffer;
  storage_kind: Generated<string>;
  width_px: number | null;
}

export interface CaptureCases {
  asset_id: number;
  available_at: Date | null;
  capture_id: string;
  category: string;
  created_at: Generated<Date>;
  current_attempt_id: string | null;
  current_reservation_id: string | null;
  delivery_consumed_at: Date | null;
  delivery_consumed_attempt_id: string | null;
  delivery_season_id: string | null;
  gc_value: number | null;
  guild_id: number;
  hol_value: number | null;
  ingested_during_season_id: string | null;
  legacy_classification: string | null;
  legacy_source_id: string | null;
  migration_status: Generated<string>;
  review_required: Generated<number>;
  row_version: Generated<number>;
  state: string;
  stock_eligibility_state: string;
  stock_expires_at: Date | null;
  stock_ineligibility_reason: string | null;
  submission_id: number;
  terminal_reason: string | null;
  updated_at: Generated<Date>;
}

export interface CaptureDeliveryConsumptions {
  attempt_id: string;
  capture_id: string;
  consumed_at: Date;
  created_at: Generated<Date>;
  delivery_season_id: string;
  discord_attachment_id: number;
  discord_message_id: number;
  fencing_token: number;
  guild_id: number;
  recorded_by_instance_id: string;
  run_item_id: string;
}

export interface CaptureEvents {
  actor_id: number | null;
  actor_type: string;
  attempt_id: string | null;
  capture_id: string;
  details_json: Json | null;
  event_id: string;
  event_type: string;
  from_state: string | null;
  guild_id: number;
  occurred_at: Date;
  reason_code: string | null;
  run_id: string | null;
  to_state: string | null;
}

export interface CaptureReservations {
  active_capture_id: string | null;
  capture_id: string;
  delivery_season_id: string;
  expires_at: Date;
  fencing_token: number;
  heartbeat_at: Date;
  leased_at: Date;
  owner_instance_id: string;
  release_reason: string | null;
  released_at: Date | null;
  reservation_id: string;
  run_item_id: string;
  state: string;
}

export interface CommunityPublicationJobs {
  attempt_count: Generated<number>;
  channel_id: number;
  completed_at: Date | null;
  created_at: Generated<Date>;
  decision_id: string | null;
  desired_content_hash: Buffer;
  guild_id: number;
  job_id: string;
  last_error_code: string | null;
  mention_policy: string;
  message_id: number | null;
  observation_window_ends_at: Date | null;
  occurrence_key: string;
  publication_kind: string;
  published_at: Date | null;
  row_version: Generated<number>;
  run_id: string | null;
  scheduled_at: Date;
  season_id: string;
  state: string;
}

export interface ConfigurationAuditEvents {
  action: string;
  actor_id: number | null;
  actor_type: string;
  after_json: Json | null;
  before_json: Json | null;
  correlation_id: string;
  event_id: string;
  guild_configuration_version_id: number | null;
  guild_id: number | null;
  occurred_at: Date;
  platform_configuration_version_id: number | null;
  subject_type: string;
}

export interface ConfigurationValidationResults {
  checks_json: Json;
  error_code: string | null;
  error_detail: string | null;
  guild_configuration_version_id: number | null;
  id: Generated<number>;
  platform_configuration_version_id: number | null;
  service_instance_id: string | null;
  service_name: string;
  status: string;
  subject_type: string;
  validated_at: Date;
}

export interface Contributors {
  error_count: Generated<number | null>;
  first_seen: Date | null;
  last_seen: Date | null;
  screenshot_count: Generated<number | null>;
  user_id: number;
  username: string | null;
}

export interface DashboardRoleAssignments {
  active_equivalent_key: Buffer | null;
  discord_user_id: number;
  expires_at: Date | null;
  granted_at: Date;
  granted_by: number;
  id: Generated<number>;
  revoked_at: Date | null;
  role: string;
  scope_guild_id: Generated<number>;
  state: string;
  updated_at: Generated<Date>;
}

export interface DashboardSchemaMigrations {
  applied_at: Date | null;
  applied_by: string | null;
  checksum: string;
  description: string | null;
  duration_ms: number | null;
  error_detail: string | null;
  finished_at: Date | null;
  last_statement_index: number | null;
  last_statement_preview: string | null;
  started_at: Date;
  state: Generated<string>;
  success: number | null;
  version: string;
}

export interface DashboardSessions {
  absolute_expires_at: Date;
  created_at: Generated<Date>;
  device_label: string | null;
  expires_at: Date;
  id: string;
  ip_hash: string | null;
  last_seen_at: Date;
  user_agent: string | null;
  user_id: number;
}

export interface DashboardSseCursor {
  created_at: Generated<Date>;
  cursor_key: string;
  last_sequence: Generated<number>;
  source_table: string;
  updated_at: Generated<Date>;
}

export interface DashboardUsers {
  avatar_hash: string | null;
  created_at: Generated<Date>;
  discord_access_token_enc: Buffer | null;
  discord_refresh_token_enc: Buffer | null;
  discord_token_expires_at: Date | null;
  discord_user_id: string;
  id: Generated<number>;
  locale: Generated<string>;
  theme_mode: Generated<string>;
  theme_name: Generated<string>;
  updated_at: Generated<Date>;
  username: string;
}

export interface DiscordIngestionCursors {
  channel_id: number;
  created_at: Generated<Date>;
  fencing_token: number | null;
  guild_id: number;
  last_catchup_completed_at: Date | null;
  last_catchup_started_at: Date | null;
  last_discord_event_at: Date | null;
  last_durable_message_id: number | null;
  last_inspected_message_id: number | null;
  overlap_from_message_id: number | null;
  owner_instance_id: string | null;
  row_version: Generated<number>;
  state: Generated<string>;
  updated_at: Generated<Date>;
}

export interface DiscordMessageCleanupJobs {
  attempt_count: Generated<number>;
  channel_id: number;
  cleanup_job_id: string;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  eligible_at: Date;
  guild_id: number;
  last_error: string | null;
  message_id: number;
  message_kind: string;
  policy_version: number;
  row_version: Generated<number>;
  state: string;
  submission_id: number;
}

export interface DiscordSubmissions {
  asset_id: number | null;
  author_name_cache: string | null;
  author_user_id: number | null;
  content_type: string | null;
  discord_created_at: Date;
  guild_id: number;
  original_filename: string;
  processed_channel_id: number | null;
  processed_deleted_at: Date | null;
  processed_message_id: number | null;
  received_at: Date;
  reception_source: string;
  row_version: Generated<number>;
  source_attachment_id: number;
  source_channel_id: number;
  source_deleted_at: Date | null;
  source_message_id: number;
  status: string;
  submission_id: Generated<number>;
  updated_at: Generated<Date>;
  url_expired_at: Date | null;
  url_snapshot: string | null;
}

export interface ForecastEvaluations {
  actual_achievement_at: Date | null;
  actual_deficit: number;
  actual_quota_achieved: number;
  actual_stock_consumed: number;
  calibration_bucket: string;
  details_json: Json | null;
  eta_error_seconds: number | null;
  evaluated_at: Date;
  evaluation_id: string;
  forecast_id: string;
  probability_error: Decimal | null;
  quality_status: string;
  stock_error: number | null;
}

export interface ForecastModelVersions {
  activated_at: Date | null;
  code_version: string;
  created_at: Generated<Date>;
  fallback_model_version_id: string | null;
  features_schema_json: Json;
  minimum_history_seasons: number;
  model_kind: string;
  model_name: string;
  model_version_id: string;
  parameters_json: Json;
  quality_metrics_json: Json | null;
  retired_at: Date | null;
  state: string;
  trained_at: Date | null;
  training_window_end: Date | null;
  training_window_start: Date | null;
  version_label: string;
}

export interface GcFreezePeriods {
  baseline_gc_hero: Generated<number>;
  baseline_gc_titan: Generated<number>;
  baseline_hero: Generated<number>;
  baseline_hol: Generated<number>;
  baseline_titan: Generated<number>;
  confidence: Decimal | null;
  ended_at: Date | null;
  freeze_id: string;
  guild_id: number;
  observed_gc_hero: number | null;
  observed_gc_titan: number | null;
  observed_hero: number | null;
  observed_hol: number | null;
  observed_titan: number | null;
  open_marker: number | null;
  reconciled_at: Date | null;
  reconciled_profile_id: string | null;
  season_id: string;
  started_at: Date;
  unknown_results: Generated<number>;
}

export interface GuildConfigBunny {
  allowed_mime_json: Json;
  catchup_interval_seconds: number;
  configuration_version_id: number;
  created_at: Generated<Date>;
  incoming_channel_id: number;
  ingestion_enabled: number;
  max_attachment_bytes: number;
  max_ocr_attempts: number;
  ocr_engine: string;
  ocr_profile: string;
  per_guild_concurrency: number;
  processed_channel_id: number | null;
  retry_base_seconds: number;
  save_processed_copy: number;
  source_delete_policy: string;
  updated_at: Generated<Date>;
}

export interface GuildConfigCommon {
  configuration_version_id: number;
  created_at: Generated<Date>;
  guild_weight: Decimal;
  locale: string;
  operational_enabled: number;
  timezone: Generated<string>;
  updated_at: Generated<Date>;
}

export interface GuildConfigOrchestrator {
  configuration_version_id: number;
  created_at: Generated<Date>;
  critical_hours_remaining: number | null;
  decision_rules_json: Json | null;
  error_rate_circuit: Decimal | null;
  fairness_weight: Decimal | null;
  hero_latency_circuit_seconds: number | null;
  max_channel_inflight: number | null;
  max_guild_inflight: number | null;
  min_sample_size: number | null;
  profile_max_seconds: number | null;
  profile_min_seconds: number | null;
  reminder_max_seconds: number | null;
  reminder_min_seconds: number | null;
  risk_eval_max_seconds: number | null;
  risk_eval_min_seconds: number | null;
  send_max_seconds: number | null;
  send_min_seconds: number | null;
  starvation_seconds: number | null;
  updated_at: Generated<Date>;
}

export interface GuildConfigSelfbot {
  auto_max_per_cycle: Generated<number>;
  auto_profile_interval_seconds: Generated<number>;
  automation_enabled: number;
  community_channel_id: number | null;
  community_updates_enabled: number;
  configuration_version_id: number;
  created_at: Generated<Date>;
  everyone_mentions_enabled: number;
  hero_response_timeout_seconds: number;
  herowarbot_channel_id: number;
  max_delivery_attempts: number;
  nb_gc_hero: Generated<number>;
  nb_gc_titan: Generated<number>;
  nb_hero: Generated<number>;
  nb_hol: Generated<number>;
  nb_titan: Generated<number>;
  profile_enabled: number;
  profile_stale_seconds: number;
  profile_timeout_seconds: number;
  reminder_enabled: number;
  screenshots_channel_id: number | null;
  updated_at: Generated<Date>;
}

export interface GuildConfigurationVersions {
  activated_at: Date | null;
  author_discord_id: number | null;
  author_type: string;
  based_on_id: number | null;
  change_summary: string | null;
  checksum: Buffer;
  created_at: Generated<Date>;
  guild_id: number;
  id: Generated<number>;
  origin: string;
  state: string;
  superseded_at: Date | null;
  validation_started_at: Date | null;
  version_no: number;
}

export interface GuildExecutionSlots {
  acquired_at: Date;
  expires_at: Date;
  fencing_token: number;
  heartbeat_at: Date;
  owner_instance_id: string;
  run_id: string;
  target_guild_id: number;
}

export interface Guilds {
  active_config_version_id: number | null;
  created_at: Generated<Date>;
  display_name_cache: string | null;
  enabled: Generated<number>;
  guild_id: number;
  priority: Generated<number>;
  row_version: Generated<number>;
  updated_at: Generated<Date>;
}

export interface GuildSeasonCategoryStatistics {
  acceptance_rate: Decimal | null;
  category: string;
  duplicate_rate: Decimal | null;
  final_count: Generated<number>;
  gc_confidence: Decimal | null;
  gc_estimate_bias: Decimal | null;
  gc_estimate_error: Decimal | null;
  hero_error_rate: Decimal | null;
  outcome_accepted: Generated<number>;
  outcome_duplicate: Generated<number>;
  outcome_hero_error: Generated<number>;
  outcome_no_usable_response: Generated<number>;
  outcome_not_validating: Generated<number>;
  outcome_unknown_correlated: Generated<number>;
  plan_id: string;
  projection_version: Generated<number>;
  quota: number;
  quota_achieved: Generated<number>;
  quota_achieved_at: Date | null;
  remaining: Generated<number>;
  start_count: Generated<number>;
  stock_carried: Generated<number>;
  stock_consumed: Generated<number>;
  stock_final: Generated<number>;
  stock_initial: Generated<number>;
  stock_new: Generated<number>;
  stock_ready: Generated<number>;
  stock_rejected: Generated<number>;
  stock_unusable: Generated<number>;
  updated_at: Generated<Date>;
  useful_yield_per_collected: Decimal | null;
  useful_yield_per_send: Decimal | null;
}

export interface GuildSeasonDailyMetrics {
  availability_ratio: Decimal | null;
  category: string;
  collected_count: Generated<number>;
  duration_ocr_ms: number | null;
  duration_reception_to_storage_ms: number | null;
  duration_response_ms: number | null;
  duration_send_ms: number | null;
  incidents_count: Generated<number>;
  metric_date_utc: Date;
  ocr_rejected_count: Generated<number>;
  ocr_valid_count: Generated<number>;
  outcomes_accepted_count: Generated<number>;
  outcomes_other_count: Generated<number>;
  plan_id: string;
  projection_version: Generated<number>;
  reminders_count: Generated<number>;
  sends_count: Generated<number>;
  stock_available_count: Generated<number>;
  updated_at: Generated<Date>;
}

export interface GuildSeasonDimensionMetrics {
  accepted_count: Generated<number>;
  available_count: Generated<number>;
  category: string;
  consumed_count: Generated<number>;
  detected_count: Generated<number>;
  dimension_key: string;
  dimension_type: string;
  metric_date_utc: Date;
  ocr_rejected_count: Generated<number>;
  ocr_valid_count: Generated<number>;
  plan_id: string;
  projection_version: Generated<number>;
  received_count: Generated<number>;
  updated_at: Generated<Date>;
}

export interface GuildSeasonPlans {
  closes_override_at_utc: Date | null;
  created_at: Generated<Date>;
  created_under_guild_configuration_version_id: number;
  guild_id: number;
  opens_override_at_utc: Date | null;
  operational_state: string;
  override_approved_by: number | null;
  override_reason: string | null;
  plan_id: string;
  quota_gc_hero: number;
  quota_gc_titan: number;
  quota_hero: number;
  quota_hol: number;
  quota_titan: number;
  row_version: Generated<number>;
  season_id: string;
  updated_at: Generated<Date>;
}

export interface GuildSeasonProgress {
  created_at: Generated<Date>;
  estimate_updated_at: Date | null;
  estimated_gc_hero: Generated<number>;
  estimated_gc_titan: Generated<number>;
  estimated_hero: Generated<number>;
  estimated_hol: Generated<number>;
  estimated_titan: Generated<number>;
  gc_freeze_open: Generated<number>;
  official_gc_hero: Generated<number>;
  official_gc_titan: Generated<number>;
  official_hero: Generated<number>;
  official_hol: Generated<number>;
  official_observed_at: Date | null;
  official_profile_id: string | null;
  official_titan: Generated<number>;
  plan_id: string;
  row_version: Generated<number>;
  status: string;
  updated_at: Generated<Date>;
}

export interface GuildSeasonStatistics {
  blocking_categories_json: Json | null;
  computed_through_event_sequence: Generated<number>;
  created_at: Generated<Date>;
  critical_categories_json: Json | null;
  downtime_by_service_json: Json | null;
  final_counters_json: Json;
  interrupted_circuits_count: Generated<number>;
  interrupted_runs_count: Generated<number>;
  latency_p50_ms: number | null;
  latency_p95_ms: number | null;
  latency_p99_ms: number | null;
  ocr_rejected: Generated<number>;
  ocr_retries: Generated<number>;
  ocr_valid: Generated<number>;
  outcome_accepted: Generated<number>;
  outcome_duplicate: Generated<number>;
  outcome_hero_error: Generated<number>;
  outcome_no_usable_response: Generated<number>;
  outcome_not_validating: Generated<number>;
  outcome_unknown_correlated: Generated<number>;
  plan_id: string;
  premiumplus_achieved: Generated<number>;
  premiumplus_achieved_at: Date | null;
  projection_version: Generated<number>;
  sends_failed: Generated<number>;
  sends_indeterminate: Generated<number>;
  sends_late: Generated<number>;
  sends_total: Generated<number>;
  start_counters_json: Json;
  stock_carried: Generated<number>;
  stock_carried_forward: Generated<number>;
  stock_consumed: Generated<number>;
  stock_initial: Generated<number>;
  stock_new: Generated<number>;
  stock_remaining: Generated<number>;
  stock_unusable: Generated<number>;
  throughput_max_per_hour: Decimal | null;
  throughput_mean_per_hour: Decimal | null;
  time_remaining_at_achievement_seconds: number | null;
  updated_at: Generated<Date>;
}

export interface GuildSeasonStockSnapshots {
  available_stock: number;
  captured_at: Date;
  carried_stock: number;
  category: string;
  expires_within_24h: number | null;
  ineligible_stock: number;
  max_age_seconds: number | null;
  median_age_seconds: number | null;
  new_stock: number;
  plan_id: string;
  snapshot_id: string;
  source: string;
}

export interface HeroDeliveryAttempts {
  attempt_id: string;
  attempt_no: number;
  capture_id: string;
  channel_id: number;
  client_send_key: string;
  consumed_at: Date | null;
  current_outcome_id: string | null;
  delivery_season_id: string;
  deterministic_filename: string;
  error_code: string | null;
  error_detail: string | null;
  guild_id: number;
  initial_outcome_at: Date | null;
  late_event_count: Generated<number>;
  prepared_at: Date;
  row_version: Generated<number>;
  run_item_id: string;
  self_attachment_id: number | null;
  self_attachment_url: string | null;
  self_message_id: number | null;
  send_started_at: Date | null;
  state: string;
  timeout_at: Date | null;
}

export interface HeroDeliveryOutcomes {
  attempt_id: string;
  confidence: Decimal | null;
  details_json: Json | null;
  hero_message_event_id: string | null;
  is_late: Generated<number>;
  observed_at: Date;
  outcome_id: string;
  outcome_kind: string;
  outcome_version: number;
  parser_version: string;
  reason_code: string | null;
  recorded_at: Date;
  supersedes_outcome_id: string | null;
}

export interface HeroDispatchAllocations {
  allocated_at: Date;
  allocation_id: string;
  attempt_id: string;
  expires_at: Date;
  fencing_token: number;
  heartbeat_at: Date;
  owner_instance_id: string;
  release_reason: string | null;
  released_at: Date | null;
  row_version: Generated<number>;
  state: string;
}

export interface HeroDispatchAllocationSlots {
  active_scope_id: number | null;
  active_scope_type: string | null;
  active_slot_no: number | null;
  allocated_at: Date;
  allocation_id: string;
  fencing_token: number;
  released_at: Date | null;
  scope_id: number;
  scope_type: string;
  slot_no: number;
  state: string;
}

export interface HeroDispatchSlots {
  created_at: Generated<Date>;
  enabled: number;
  row_version: Generated<number>;
  scope_id: number;
  scope_type: string;
  slot_no: number;
}

export interface HeroMessageEvents {
  author_id: number;
  channel_id: number;
  classification: string;
  confidence: Decimal | null;
  deleted_at: Date | null;
  discord_created_at: Date;
  edited_at: Date | null;
  event_id: string;
  event_kind: string;
  guild_id: number;
  message_id: number;
  observed_at: Date;
  parser_version: string;
  raw_payload_json: Json;
  related_attachment_id: number | null;
  review_status: string;
}

export interface HerowarbotCommunityMessages {
  channel_id: number;
  created_at: Generated<Date>;
  guild_id: number;
  last_reminder_at: Date | null;
  last_status_at: Date | null;
  next_reminder_at: Date | null;
  reminder_message_id: number | null;
  reminder_message_id_fr: number | null;
  status_message_id: number | null;
  target_season: string | null;
  updated_at: Generated<Date>;
}

export interface HerowarbotEvents {
  attachment_id: number | null;
  channel_id: number;
  created_at: Date;
  detail: string | null;
  event_kind: string;
  guild_id: number;
  id: Generated<number>;
  message_id: number;
  observed_at: Generated<Date>;
}

export interface HerowarbotProfiles {
  channel_id: number;
  created_at: Generated<Date>;
  description: string;
  guild_id: number;
  hero_current: number | null;
  hero_target: number | null;
  hol_current: number | null;
  hol_target: number | null;
  id: Generated<number>;
  message_id: number;
  received_at: Date;
  requesting_user_id: number | null;
  target_season: string;
  titan_current: number | null;
  titan_target: number | null;
}

export interface HerowarbotSubmissions {
  attachment_id: number;
  attachment_url: string | null;
  channel_id: number;
  correlation_confidence: Generated<string>;
  created_at: Generated<Date>;
  filename: string;
  guild_id: number;
  id: Generated<number>;
  local_screenshot_id: number | null;
  quota_confirmed_at: Date | null;
  responded_at: Date | null;
  response_detail: string | null;
  response_kind: string | null;
  response_message_id: number | null;
  run_id: string | null;
  source_message_id: number;
  source_user_id: number | null;
  status: Generated<string>;
  submitted_at: Date;
  target_season: string;
  updated_at: Generated<Date>;
}

export interface HerowarbotSyncState {
  channel_id: number;
  created_at: Generated<Date>;
  guild_id: number;
  last_message_id: number | null;
  last_reconciled_at: Date | null;
  updated_at: Generated<Date>;
}

export interface Incidents {
  acknowledged_at: Date | null;
  acknowledged_by: number | null;
  capture_id: string | null;
  dedup_key: string;
  details_json: Json | null;
  first_seen_at: Date;
  guild_id: number | null;
  incident_id: string;
  last_seen_at: Date;
  occurrence_count: Generated<number>;
  open_dedup_key: string | null;
  recommended_action: string | null;
  resolved_at: Date | null;
  resolved_by: number | null;
  row_version: Generated<number>;
  run_id: string | null;
  service_name: string | null;
  severity: string;
  status: string;
  summary: string;
}

export interface IntegrationConsumerInbox {
  aggregate_id: string;
  aggregate_type: string;
  aggregate_version: number;
  consumer_name: string;
  effect_reference_id: string | null;
  effect_reference_type: string | null;
  event_id: string;
  processed_at: Date;
}

export interface IntegrationConsumerOffsets {
  consumer_name: string;
  error_code: string | null;
  heartbeat_at: Date;
  last_processed_at: Date;
  last_sequence_id: number;
  row_version: Generated<number>;
}

export interface IntegrationDeliveryAttempts {
  attempt_id: string;
  attempt_no: number;
  backoff_seconds: number | null;
  correlation_id: string;
  delivery_id: string;
  error_code: string | null;
  error_detail: string | null;
  finished_at: Date | null;
  outcome: string;
  started_at: Date;
  worker_instance_id: string;
}

export interface IntegrationEventDeliveries {
  attempt_count: Generated<number>;
  completed_at: Date | null;
  consumer_name: string;
  created_at: Generated<Date>;
  dead_lettered_at: Date | null;
  delivery_id: string;
  event_id: string;
  last_error_code: string | null;
  last_error_detail: string | null;
  lease_expires_at: Date | null;
  lease_fencing_token: number | null;
  lease_owner_instance_id: string | null;
  manually_resumed_at: Date | null;
  max_attempts: number;
  next_retry_at: Date | null;
  row_version: Generated<number>;
  state: string;
  updated_at: Generated<Date>;
}

export interface IntegrationEvents {
  aggregate_id: string;
  aggregate_type: string;
  aggregate_version: number;
  available_at: Date;
  created_at: Generated<Date>;
  event_id: string;
  event_type: string;
  expires_at: Date | null;
  guild_id: number | null;
  payload_json: Json;
  producer: string;
  producer_event_key: string;
  sequence_id: Generated<number>;
}

export interface LegacyCaptureProjection {
  capture_id: string;
  created_at: Generated<Date>;
  desired_reason: string;
  desired_used: number;
  last_applied_at: Date | null;
  last_error: string | null;
  last_verified_at: Date | null;
  legacy_classification: string;
  legacy_screenshot_id: number;
  legacy_source_id: string;
  migration_status: string;
  mismatch_count: Generated<number>;
  observed_used: number | null;
  projection_state: string;
  review_required: Generated<number>;
  row_version: Generated<number>;
  terminal_reason: string | null;
  updated_at: Generated<Date>;
}

export interface OcrAttempts {
  attempt_id: string;
  attempt_no: number;
  duration_ms: number | null;
  engine: string;
  engine_version: string;
  error_code: string | null;
  error_detail: string | null;
  finished_at: Date | null;
  job_id: string;
  parser_version: string;
  raw_result_json: Json | null;
  started_at: Date;
  state: string;
  worker_instance_id: string | null;
}

export interface OcrJobs {
  attempt_count: Generated<number>;
  confidence: Decimal | null;
  created_at: Generated<Date>;
  extracted_json: Json | null;
  final_category: string | null;
  final_gc: number | null;
  final_hol: number | null;
  job_id: string;
  last_error_code: string | null;
  next_retry_at: Date | null;
  parser_version: string | null;
  row_version: Generated<number>;
  selected_attempt_id: string | null;
  state: string;
  submission_id: number;
  updated_at: Generated<Date>;
}

export interface OfficialProfiles {
  channel_id: number;
  description_snapshot: string | null;
  gc_hero: Generated<number>;
  gc_titan: Generated<number>;
  guild_id: number;
  hero: Generated<number>;
  hol: Generated<number>;
  is_final_profile: number;
  is_valid: number;
  message_id: number;
  parser_version: string;
  profile_id: string;
  raw_payload_json: Json;
  received_at: Date;
  requested_by: string;
  season_id: string;
  titan: Generated<number>;
}

export interface OperatorAuditLog {
  action: string;
  actor_discord_id: number;
  actor_role: string;
  after_json: Json | null;
  audit_id: string;
  before_json: Json | null;
  correlation_id: string;
  error_code: string | null;
  guild_id: number | null;
  idempotency_key: string;
  occurred_at: Date;
  request_json: Json;
  status: string;
  target_id: string;
  target_type: string;
}

export interface OperatorCommandAttempts {
  attempt_id: string;
  attempt_no: number;
  command_id: string;
  error_code: string | null;
  error_detail: string | null;
  fencing_token: number;
  finished_at: Date | null;
  outcome: string;
  result_json: Json | null;
  retry_at: Date | null;
  service_instance_id: string;
  started_at: Date;
}

export interface OperatorCommandEvents {
  actor_id: number | null;
  actor_type: string;
  command_id: string;
  details_json: Json | null;
  event_id: string;
  event_type: string;
  from_state: string | null;
  occurred_at: Date;
  to_state: string | null;
}

export interface OperatorCommands {
  attempt_count: Generated<number>;
  available_at: Date;
  command_id: string;
  command_type: string;
  completed_at: Date | null;
  created_at: Generated<Date>;
  expires_at: Date | null;
  guild_id: number | null;
  idempotency_key: string;
  last_error_code: string | null;
  last_error_detail: string | null;
  lease_expires_at: Date | null;
  lease_fencing_token: number | null;
  lease_owner_instance_id: string | null;
  max_attempts: number;
  payload_json: Json;
  preconditions_json: Json | null;
  priority: number;
  requested_by_discord_id: number;
  requested_by_role: string;
  result_json: Json | null;
  row_version: Generated<number>;
  season_id: string | null;
  started_at: Date | null;
  state: string;
  target_id: string | null;
  target_service: string;
  target_type: string | null;
}

export interface OrchestrationDecisions {
  action: string;
  blocked_reason: string | null;
  cadences_json: Json;
  capacity_json: Json;
  carried_stock: number;
  category: string | null;
  decision_id: string;
  engine_version: string;
  evaluated_at: Date;
  expected_yield: Decimal;
  forecast_confidence: Decimal;
  forecast_snapshot_id: string | null;
  guild_configuration_version_id: number | null;
  guild_id: number;
  hours_remaining: Decimal;
  inputs_json: Json;
  next_evaluation_at: Date;
  platform_configuration_version_id: number | null;
  quota_remaining: number;
  ready_stock: number;
  risk_band: string;
  risk_score: Decimal;
  rules_triggered_json: Json;
  season_id: string;
}

export interface PlatformConfigurationState {
  activated_at: Date;
  active_version_id: number;
  created_at: Generated<Date>;
  row_version: Generated<number>;
  singleton_id: number;
  updated_at: Generated<Date>;
}

export interface PlatformConfigurationVersions {
  activated_at: Date | null;
  author_discord_id: number | null;
  based_on_id: number | null;
  change_summary: string | null;
  checksum: Buffer;
  created_at: Generated<Date>;
  id: Generated<number>;
  state: string;
  superseded_at: Date | null;
  version_no: number;
}

export interface PlatformOrchestratorDefaults {
  configuration_version_id: number;
  created_at: Generated<Date>;
  decision_rules_json: Json | null;
  default_max_channel_inflight: number;
  default_max_guild_inflight: number;
  default_safety_stock_ratio: Generated<Decimal>;
  error_rate_circuit: Decimal;
  fairness_weight: Decimal;
  forecast_auto_confidence_threshold: Generated<Decimal>;
  forecast_min_history_seasons: Generated<number>;
  forecast_min_outcomes_per_category: Generated<number>;
  hero_latency_circuit_seconds: number;
  profile_max_seconds: number;
  profile_min_seconds: number;
  reminder_max_seconds: number;
  reminder_min_seconds: number;
  risk_eval_max_seconds: number;
  risk_eval_min_seconds: number;
  send_max_seconds: number;
  send_min_seconds: number;
  starvation_seconds: number;
  updated_at: Generated<Date>;
}

export interface PlatformRuntimeConfig {
  audit_retention_days: number;
  blob_grace_after_consumption_hours: Generated<number>;
  blob_grace_after_terminal_ocr_reject_hours: Generated<number>;
  configuration_version_id: number;
  created_at: Generated<Date>;
  dispatch_ttl_seconds: number;
  event_backoff_base_seconds: number;
  event_backoff_max_seconds: number;
  event_max_attempts: number;
  hard_safety_json: Json | null;
  max_global_hero_inflight: Generated<number>;
  max_global_ocr_workers: Generated<number>;
  metadata_retention_days: number;
  operator_command_ttl_seconds: number;
  reservation_ttl_seconds: number;
  singleton_ttl_seconds: number;
  statistics_retention_days: number;
  updated_at: Generated<Date>;
}

export interface ReminderObservationWindows {
  captures_after: number | null;
  captures_before: number;
  causality_claimed: Generated<number>;
  computed_at: Date;
  correlation_score: Decimal | null;
  observed_gain: number | null;
  plan_id: string;
  publication_job_id: string;
  reaction_delay_p50_seconds: number | null;
  stock_after: number | null;
  stock_before: number;
  window_end: Date;
  window_start: Date;
}

export interface SchemaMigrations {
  applied_at: Date | null;
  applied_by: string | null;
  checksum: Buffer;
  description: string | null;
  duration_ms: number | null;
  error_detail: string | null;
  finished_at: Date | null;
  last_statement_index: number | null;
  last_statement_preview: string | null;
  started_at: Date;
  state: Generated<string>;
  success: number | null;
  version: string;
}

export interface ScreenshotErrors {
  date: Date;
  filename: string;
  id: Generated<number>;
  reason: string | null;
  user_id: number | null;
  username: string | null;
}

export interface Screenshots {
  date: Date;
  filename: string;
  GC: number | null;
  guild_id: number;
  HOL: number | null;
  id: Generated<number>;
  image_data: Buffer | null;
  message_id: number;
  screen_hash: string;
  TypeDeCombat: string;
  url_image: string | null;
  used: Generated<number | null>;
  user_id: number | null;
  username: string | null;
}

export interface ScreenshotsHistory {
  date: Date | null;
  guild_id: number | null;
  HOL: number | null;
  screen_hash: string;
  TypeDeCombat: string | null;
  user_id: number | null;
  username: string | null;
}

export interface ScreenshotsOCRFailed {
  failure_date: Date;
  filename: string;
  guild_id: number;
  id: Generated<number>;
  image_data: Buffer;
  last_retry_date: Date | null;
  message_id: number | null;
  retry_count: Generated<number | null>;
  screen_hash: string;
  url_image: string | null;
  user_id: number | null;
  username: string | null;
}

export interface SeasonForecastSnapshots {
  as_of_at: Date;
  carried_stock: number;
  category: string;
  collection_rate: Decimal | null;
  confidence_level: string;
  confidence_score: Decimal | null;
  created_at: Generated<Date>;
  estimated_quota_achievement_at: Date | null;
  estimated_stock_exhaustion_at: Date | null;
  estimated_stock_required: number | null;
  expected_duplicate_rate: Decimal | null;
  expected_error_rate: Decimal | null;
  features_json: Json;
  forecast_id: string;
  forecast_kind: string;
  historical_yield: Decimal | null;
  horizon_at: Date;
  input_facts_through_sequence: number;
  model_version_id: string;
  output_json: Json;
  plan_id: string;
  predicted_deficit: number | null;
  premiumplus_probability: Decimal | null;
  quota_remaining: number;
  ready_stock: number;
  recent_yield: Decimal | null;
  send_rate: Decimal | null;
}

export interface SeasonLearningRecommendations {
  applied_configuration_version_id: number | null;
  approved_by: number | null;
  category: string | null;
  confidence_level: string;
  created_at: Generated<Date>;
  current_value_json: Json;
  decided_at: Date | null;
  guild_id: number;
  parameter_key: string;
  platform_max_json: Json | null;
  platform_min_json: Json | null;
  proposed_value_json: Json;
  rationale_json: Json;
  recommendation_id: string;
  source_plan_id: string;
  state: string;
  target_plan_id: string | null;
}

export interface SeasonReportVersions {
  created_at: Generated<Date>;
  current_plan_id: string | null;
  facts_through_sequence: number;
  is_current: Generated<number>;
  plan_id: string;
  published_at: Date;
  reason: string;
  recommendations_json: Json | null;
  report_id: string;
  report_version: number;
  summary_json: Json;
  supersedes_report_id: string | null;
}

export interface SeasonStatistics {
  computed_through_event_sequence: Generated<number>;
  created_at: Generated<Date>;
  guilds_failed: Generated<number>;
  guilds_premiumplus_achieved: Generated<number>;
  guilds_total: Generated<number>;
  projection_version: Generated<number>;
  season_id: string;
  total_accepted: Generated<number>;
  total_collected: Generated<number>;
  total_consumed: Generated<number>;
  total_duplicate: Generated<number>;
  total_error: Generated<number>;
  total_no_usable_response: Generated<number>;
  total_not_validating: Generated<number>;
  total_stock: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ServiceGuildStatus {
  applied_config_version_id: number | null;
  backlog_count: Generated<number>;
  guild_id: number;
  health: string;
  instance_id: string;
  last_catchup_at: Date | null;
  last_db_at: Date | null;
  last_discord_at: Date | null;
  last_error_at: Date | null;
  last_error_code: string | null;
  last_profile_at: Date | null;
  mode: string;
  row_version: Generated<number>;
  service_name: string;
  updated_at: Generated<Date>;
}

export interface ServiceInstances {
  heartbeat_at: Date;
  host_fingerprint: string;
  instance_id: string;
  process_fingerprint: string;
  service_name: string;
  service_version: string;
  started_at: Date;
  state: string;
  stopped_at: Date | null;
  supported_schema_max: number;
  supported_schema_min: number;
}

export interface SingletonLeases {
  acquired_at: Date;
  expires_at: Date;
  fencing_token: number;
  heartbeat_at: Date;
  lease_key: string;
  owner_instance_id: string;
  payload_json: Json | null;
}

export interface StatisticsProjectionCheckpoints {
  last_error: string | null;
  last_event_sequence: Generated<number>;
  last_rebuild_completed_at: Date | null;
  last_rebuild_started_at: Date | null;
  projection_name: string;
  projection_version: Generated<number>;
  row_version: Generated<number>;
  state: string;
  updated_at: Generated<Date>;
}

export interface SubmissionSeasons {
  boundary_confidence: Decimal;
  boundary_source: string;
  closed_at_utc: Date | null;
  closed_with_estimated_result: Generated<number>;
  created_at: Generated<Date>;
  final_profile_received_at: Date | null;
  final_result_confirmed: Generated<number>;
  late_events_count: Generated<number>;
  open_for_delivery_marker: number | null;
  opens_at_utc: Date;
  operational_closes_at_utc: Date;
  planned_closes_at_utc: Date;
  premiumplus_target_key: string;
  row_version: Generated<number>;
  season_id: string;
  state: string;
  submission_period_key: string;
  updated_at: Generated<Date>;
}

export interface DB {
  asset_retention_holds: AssetRetentionHolds;
  automation_run_events: AutomationRunEvents;
  automation_run_items: AutomationRunItems;
  automation_runs: AutomationRuns;
  blob_purge_events: BlobPurgeEvents;
  blob_purge_jobs: BlobPurgeJobs;
  capture_asset_blobs: CaptureAssetBlobs;
  capture_assets: CaptureAssets;
  capture_cases: CaptureCases;
  capture_delivery_consumptions: CaptureDeliveryConsumptions;
  capture_events: CaptureEvents;
  capture_reservations: CaptureReservations;
  community_publication_jobs: CommunityPublicationJobs;
  configuration_audit_events: ConfigurationAuditEvents;
  configuration_validation_results: ConfigurationValidationResults;
  contributors: Contributors;
  dashboard_role_assignments: DashboardRoleAssignments;
  dashboard_schema_migrations: DashboardSchemaMigrations;
  dashboard_sessions: DashboardSessions;
  dashboard_sse_cursor: DashboardSseCursor;
  dashboard_users: DashboardUsers;
  discord_ingestion_cursors: DiscordIngestionCursors;
  discord_message_cleanup_jobs: DiscordMessageCleanupJobs;
  discord_submissions: DiscordSubmissions;
  forecast_evaluations: ForecastEvaluations;
  forecast_model_versions: ForecastModelVersions;
  gc_freeze_periods: GcFreezePeriods;
  guild_config_bunny: GuildConfigBunny;
  guild_config_common: GuildConfigCommon;
  guild_config_orchestrator: GuildConfigOrchestrator;
  guild_config_selfbot: GuildConfigSelfbot;
  guild_configuration_versions: GuildConfigurationVersions;
  guild_execution_slots: GuildExecutionSlots;
  guild_season_category_statistics: GuildSeasonCategoryStatistics;
  guild_season_daily_metrics: GuildSeasonDailyMetrics;
  guild_season_dimension_metrics: GuildSeasonDimensionMetrics;
  guild_season_plans: GuildSeasonPlans;
  guild_season_progress: GuildSeasonProgress;
  guild_season_statistics: GuildSeasonStatistics;
  guild_season_stock_snapshots: GuildSeasonStockSnapshots;
  guilds: Guilds;
  hero_delivery_attempts: HeroDeliveryAttempts;
  hero_delivery_outcomes: HeroDeliveryOutcomes;
  hero_dispatch_allocation_slots: HeroDispatchAllocationSlots;
  hero_dispatch_allocations: HeroDispatchAllocations;
  hero_dispatch_slots: HeroDispatchSlots;
  hero_message_events: HeroMessageEvents;
  herowarbot_community_messages: HerowarbotCommunityMessages;
  herowarbot_events: HerowarbotEvents;
  herowarbot_profiles: HerowarbotProfiles;
  herowarbot_submissions: HerowarbotSubmissions;
  herowarbot_sync_state: HerowarbotSyncState;
  incidents: Incidents;
  integration_consumer_inbox: IntegrationConsumerInbox;
  integration_consumer_offsets: IntegrationConsumerOffsets;
  integration_delivery_attempts: IntegrationDeliveryAttempts;
  integration_event_deliveries: IntegrationEventDeliveries;
  integration_events: IntegrationEvents;
  legacy_capture_projection: LegacyCaptureProjection;
  ocr_attempts: OcrAttempts;
  ocr_jobs: OcrJobs;
  official_profiles: OfficialProfiles;
  operator_audit_log: OperatorAuditLog;
  operator_command_attempts: OperatorCommandAttempts;
  operator_command_events: OperatorCommandEvents;
  operator_commands: OperatorCommands;
  orchestration_decisions: OrchestrationDecisions;
  platform_configuration_state: PlatformConfigurationState;
  platform_configuration_versions: PlatformConfigurationVersions;
  platform_orchestrator_defaults: PlatformOrchestratorDefaults;
  platform_runtime_config: PlatformRuntimeConfig;
  reminder_observation_windows: ReminderObservationWindows;
  schema_migrations: SchemaMigrations;
  screenshot_errors: ScreenshotErrors;
  screenshots: Screenshots;
  screenshots_history: ScreenshotsHistory;
  screenshots_OCR_failed: ScreenshotsOCRFailed;
  season_forecast_snapshots: SeasonForecastSnapshots;
  season_learning_recommendations: SeasonLearningRecommendations;
  season_report_versions: SeasonReportVersions;
  season_statistics: SeasonStatistics;
  service_guild_status: ServiceGuildStatus;
  service_instances: ServiceInstances;
  singleton_leases: SingletonLeases;
  statistics_projection_checkpoints: StatisticsProjectionCheckpoints;
  submission_seasons: SubmissionSeasons;
}
